content-type:
  org:
    input-files: ["/home/saba/notes/notes.org", "/home/saba/notes/writing.org"]
    input-filter: null
    compressed-jsonl: ".notes.json.gz"
    embeddings-file: ".note_embeddings.pt"

  # ledger:
  #   input-files: /home/projects/personal-finance/bon.beancount
  #   input-filter: null
  #   compressed-jsonl: .transactions.jsonl.gz
  #   embeddings-file: .transaction_embeddings.pt

  # image:
  #   input-directory: "tests/data"
  #   embeddings-file: "tests/data/.image_embeddings.pt"
  #   batch-size: 50
  #   use-xmp-metadata: "no"

  # music:
  #   input-files: ["tests/data/music.org"]
  #   input-filter: null
  #   compressed-jsonl: "tests/data/.songs.jsonl.gz"
  #   embeddings-file: "tests/data/.song_embeddings.pt"

search-type:
  asymmetric:
    encoder: "sentence-transformers/msmarco-MiniLM-L-6-v3"
    cross-encoder: "cross-encoder/ms-marco-MiniLM-L-6-v2"

  image:
    encoder: "clip-ViT-B-32"
