content_type:
  image: null
  ledger: null
  music: null
  org:
    compressed_jsonl: .notes.json.gz
    embeddings_file: .note_embeddings.pt
    input_files:
    - /home/saba/notes/notes.org
    - /home/saba/notes/writing.org
    input_filter: null
processor:
  conversation:
    conversation_history: ''
    conversation_logfile: .conversation_logs.json
    open_api_key: null
search_type:
  asymmetric:
    cross_encoder: cross-encoder/ms-marco-MiniLM-L-6-v2
    encoder: sentence-transformers/msmarco-MiniLM-L-6-v3
  image:
    encoder: clip-ViT-B-32
