content-type:
  image: null
  ledger: null
  music: null
  org:
    compressed-jsonl: .notes.json.gz
    embeddings-file: .note_embeddings.pt
    input-files:
    - /home/saba/notes/notes.org
    - /home/saba/notes/writing.org
    input-filter: null
processor:
  conversation:
    conversation-history: ''
    conversation-logfile: .conversation_logs.json
    open-api-key: null
search-type:
  asymmetric:
    cross-encoder: cross-encoder/ms-marco-MiniLM-L-6-v2
    encoder: sentence-transformers/msmarco-MiniLM-L-6-v3
  image:
    encoder: ''
