version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8000
    ports:
      # If changing the local port (left hand side), no other changes required.
      # If changing the remote port (right hand side), 
      #   change the port in the args in the build section, 
      #   as well as the port in the command section to match
      - "8000:8000"
    working_dir: /app
    volumes:
      - .:/app
      # These mounted volumes hold the raw data that should be indexed for search. 
      # The path in your local directory (left hand side)
      #   points to the files you want to index.
      # The path of the mounted directory (right hand side),
      #   must match the path prefix in your config file.
      - ./tests/data/:/data/notes/
      - ./tests/data/:/data/images/
      - ./tests/data/:/data/ledger/
      - ./tests/data/:/data/music/
      # It's ok if you don't have existing embeddings. 
      # You can set this volume to point to an empty folder.
      - ./tests/data/embeddings/:/data/generated/

    # Use 0.0.0.0 to explicitly set the host ip for the service on the container. https://pythonspeed.com/articles/docker-connection-refused/
    command: --host="0.0.0.0" --port=8000 -c=docker_sample_config.yml -vv
