* Emacs Ridge
  /An Emacs interface for [[https://github.com/debanjum/ridge][Ridge]]/

** Requirements
   - Install and Run [[https://github.com/debanjum/ridge][Ridge]]

** Installation
   - Direct Install
     - Put ~ridge.el~ in your Emacs load path. For e.g ~/.emacs.d/lisp

     - Load via ~use-package~ in your ~/.emacs.d/init.el or .emacs file by adding below snippet
       #+begin_src elisp
         ;; Ridge Package
         (use-package ridge
           :load-path "~/.emacs.d/lisp/ridge.el"
           :bind ("C-c s" . 'ridge))
       #+end_src

   - With [[https://github.com/raxod502/straight.el][straight.el]]
     - Add below snippet to your ~/.emacs.d/init.el or .emacs config file and execute it.
       #+begin_src elisp
         ;; Ridge Package for Semantic Search
         (use-package ridge
           :after org
           :straight (ridge :type git :host github :repo "debanjum/ridge" :files (:defaults "src/interface/emacs/ridge.el"))
           :bind ("C-c s" . 'ridge))
       #+end_src

   - With [[https://github.com/quelpa/quelpa#installation][Quelpa]]
     - Ensure [[https://github.com/quelpa/quelpa#installation][Quelpa]], [[https://github.com/quelpa/quelpa-use-package#installation][quelpa-use-package]] are installed
     - Add below snippet to your ~/.emacs.d/init.el or .emacs config file and execute it.
       #+begin_src elisp
         ;; Ridge Package
         (use-package ridge
           :after org
           :quelpa (ridge :fetcher url :url "https://raw.githubusercontent.com/debanjum/ridge/master/src/interface/emacs/ridge.el")
           :bind ("C-c s" . 'ridge))
       #+end_src

** Usage
   1. Open Query Interface on Client

       - In Emacs: Call ~ridge~ using keybinding ~C-c s~ or ~M-x ridge~
       - On Web: Open http://localhost:8000/

   2. Query Incrementally in Natural Language

      e.g "What is the meaning of life?" "What are my life goals?"

   3. Apply filters to narrow down results further

      Include/Exclude specific words or date range from results by updating query with below query format

      e.g `What is the meaning of life? -god +none dt:"last week"`
