name: semantic-search
channels:
  - conda-forge
dependencies:
  - python=3.8.*
  - numpy=1.22.4
  - pytorch=1.11.0
  - transformers=4.19.4
  - sentence-transformers=2.1.0
  - fastapi=0.77.1
  - uvicorn=0.17.6
  - pyyaml=6.0
  - pytest=7.1.2
  - pillow=8.4.0
  - torchvision=0.12.0
  - openai=0.20.0
  - pydantic=1.9.1
  - jinja2=3.1.2
  - aiofiles=0.8.0
  - huggingface_hub=0.8.1
