name: semantic-search
channels:
  - conda-forge
dependencies:
  - python=3.*
  - numpy=1.*
  - pytorch=1.*
  - transformers=4.*
  - sentence-transformers=2.1.0
  - fastapi=0.*
  - uvicorn=0.*
  - pyyaml=5.*
  - pytest=6.*
  - pillow=8.*
  - torchvision=0.*
  - openai=0.*
  - pydantic=1.*
  - jinja2=3.0.*
  - aiofiles=0.*
  - huggingface_hub=0.*