# melpa quality checks like checkdoc, byte-compile, package-lint for ridge.el
# using melpazoid: https://github.com/riscy/melpazoid

name: build ridge.el
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
