name: test

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - src/**
      - tests/**
      - config/**
      - setup.py
      - .github/workflows/test.yml
  push:
    branches:
      - 'master'
    paths:
      - src/**
      - tests/**
      - config/**
      - setup.py
      - .github/workflows/test.yml

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install --upgrade .

      - name: Test with pytest
        run: |
          pytest 